# Site settings
title:          CYOD
description:    "Personalized Learning, Personalized Technology"
baseurl:        "/"
url:            "https://cyod.xyz"

# Author
author:
  name:         swoicik
  url:          https://swoicik.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year/:title
paginate:       10
